  # Kong instance
  - name: kong-instance
    type: compute.v1.instance
    properties:
      zone: us-central1-a
      machineType: https://www.googleapis.com/compute/v1/projects/isis2503-talleres-415101/zones/us-central1-a/machineTypes/e2-micro
      disks:
      - deviceName: boot
        type: PERSISTENT
        boot: true
        autoDelete: true
        initializeParams:
          sourceImage:  https://www.googleapis.com/compute/v1/projects/cos-cloud/global/images/cos-101-17162-463-8
      networkInterfaces:
      - network: https://www.googleapis.com/compute/v1/projects/isis2503-talleres-415101/global/networks/default
        networkIP: 10.128.0.81
        accessConfigs:
        - name: External NAT
          type: ONE_TO_ONE_NAT
      tags:
        items: 
        - msd-api-gateway
      metadata:
        items:
        - key: startup-script
          value: |
            #!/bin/bash
            sudo mkdir /home/labs
            cd /home/labs
            sudo git clone https://github.com/Arquitectura-SW/SolicitudesApplication.git
            cd SolicitudesApplication
            docker network create kong-net
            docker run -d --name kong --network=kong-net --restart=always \
            -v "$(pwd):/kong/declarative/" -e "KONG_DATABASE=off" \
            -e "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yaml" \
            -p 8000:8000 kong/kong-gateway